version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Porta de comunicação do RabbitMQ
      - "15672:15672"  # Porta para acessar a UI de gerenciamento do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  almoxarifado-service:
    image: almoxarifado-service:latest
    build:
      context: ./almoxarifado-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  transporte-service:
    image: transporte-service:latest
    build:
      context: ./transporte-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
